package app.getknit.knit.data.emoji

import app.getknit.knit.ui.chat.emojiOnlyCount
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File
import java.text.BreakIterator

/**
 * Contract test for the shipped `emoji/emoji_en.tsv` asset (generated by `scripts/gen-emoji-catalog.py`
 * from the vendored Unicode `emoji-test.txt`). Read straight from disk like `WordListTest` and parsed with
 * the production [EmojiCatalogParser] — a plain JVM test. The invariants are what stop a regeneration from
 * silently shipping a broken grid: a dropped line, a tone variant in browse, a duplicate key, a string that
 * isn't one emoji, or a separator character the recents codec would split on.
 */
class EmojiCatalogAssetTest {
    private val file: File by lazy {
        listOf("src/main/assets/emoji/emoji_en.tsv", "app/src/main/assets/emoji/emoji_en.tsv")
            .map(::File)
            .firstOrNull { it.exists() }
            ?: error("emoji_en.tsv not found (cwd=${File(".").absolutePath})")
    }
    private val entries: List<EmojiEntry> by lazy { file.bufferedReader().useLines(EmojiCatalogParser::parse) }
    private val catalog: EmojiCatalog by lazy { EmojiCatalog(entries) }

    @Test
    fun everyDataLineParsesAndTheCatalogIsFullSized() {
        val dataLines = file.readLines().count { it.isNotBlank() && !it.startsWith("#") }
        assertEquals("a dropped line means a malformed row or an unknown group", dataLines, entries.size)
        assertTrue("Emoji 17.0 ships 3,944 fully-qualified emoji; got ${entries.size}", entries.size >= 3_500)
        assertTrue("browse (no tone variants) should be ~1,900; got ${catalog.browse.size}", catalog.browse.size >= 1_500)
    }

    @Test
    fun toneVariantsAreFlaggedExactlyWhenTheyCarryAModifier() {
        entries.forEach { e ->
            val hasModifier = e.emoji.codePoints().anyMatch { it in SKIN_TONES }
            assertEquals("tone flag mismatch on '${e.name}'", hasModifier, e.toneVariant)
        }
        assertTrue(catalog.browse.none { it.toneVariant })
    }

    @Test
    fun keysAreUniqueAndFreeOfSeparators() {
        assertEquals("grid keys are the emoji strings", entries.size, entries.map { it.emoji }.toHashSet().size)
        entries.forEach { e ->
            assertFalse("'${e.name}' contains a tab/newline/unit separator", e.emoji.any { it in SEPARATORS })
            assertFalse("'${e.name}' name contains a separator", e.name.any { it in SEPARATORS })
            assertTrue(e.emoji.isNotBlank() && e.name.isNotBlank())
        }
    }

    @Test
    fun everyEntryIsExactlyOneEmojiGrapheme() {
        val boundary = BreakIterator.getCharacterInstance()
        val multiCluster =
            entries.filter { e ->
                boundary.setText(e.emoji)
                boundary.first()
                boundary.next() != e.emoji.length
            }
        assertTrue("not one grapheme cluster: ${multiCluster.take(10).map { it.name }}", multiCluster.isEmpty())
        // The jumbomoji detector must agree, or a message that is just this emoji renders at body size.
        val notEmoji = entries.filter { emojiOnlyCount(it.emoji) != 1 }
        assertTrue("emojiOnlyCount rejects ${notEmoji.size}: ${notEmoji.take(15).map { it.name }}", notEmoji.isEmpty())
    }

    @Test
    fun theClassicSixAreBaseEntries() {
        RecentReactions.DEFAULTS.forEach { d ->
            val e = entries.firstOrNull { it.emoji == d } ?: error("default '$d' missing from the catalog")
            assertFalse(e.toneVariant)
        }
    }

    @Test
    fun orderGroupsAndComponentsMatchTheGenerator() {
        assertEquals("Unicode order is preserved: grinning face first", "😀", entries.first().emoji)
        assertEquals(9, EmojiGroup.entries.size)
        assertEquals("every group has renderable base emoji", EmojiGroup.entries.toSet(), catalog.byGroup.keys)
        val scotland = "🏴󠁧󠁢󠁳󠁣󠁴󠁿"
        assertEquals(EmojiGroup.FLAGS, entries.first { it.emoji == scotland }.group)
        assertTrue("a bare skin-tone swatch is a component, not an emoji", entries.none { it.emoji == "🏻" })
        assertTrue("a bare hair component is not an emoji", entries.none { it.emoji == "🦰" })
    }

    private companion object {
        val SKIN_TONES = 0x1F3FB..0x1F3FF
        val SEPARATORS = setOf('\t', '\n', RecentReactions.SEPARATOR)
    }
}
