package app.getknit.knit.ui.theme

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color
import kotlin.math.abs
import kotlin.math.atan2
import kotlin.math.cbrt
import kotlin.math.cos
import kotlin.math.hypot
import kotlin.math.min
import kotlin.math.pow
import kotlin.math.sign
import kotlin.math.sin

/**
 * The colours a photo-less avatar wears: the disc's [container] and the initial's [onContainer], a
 * container/on-container pair at Material's own tones (disc 85 / letter 10 in light, disc 30 / letter 90
 * in dark) so the initial clears text contrast by construction — `ColorSchemeTest` measures it.
 *
 * Which tint an identity gets is [avatarTintIndex]'s business; the palette itself is generated by
 * `scripts/gen-avatar-palette.py` (twelve hues 30° apart in HCT, chroma capped at what the weakest hue
 * can reach so no disc is louder than its neighbours) and lives in [KnitSemanticColors] rather than the
 * colour scheme, because an identity's colour must not follow the wallpaper: the point of keying it on
 * the node id is that Ada is the same green in your list, in your notification shade, and on Bob's
 * phone. ADR 2026-09.j8c7. Under Material You the whole palette is [harmonizedToward] the wallpaper's
 * primary at theme time instead — a bounded nudge that keeps Ada a green, just the wallpaper's kind.
 */
@Immutable
data class AvatarTint(
    val container: Color,
    val onContainer: Color,
) {
    /**
     * This tint steered toward [accent] the way Material harmonizes a custom colour under Material You
     * (`Blend.harmonize`): the hue rotates toward the accent's by half their difference and never more
     * than [MAX_HARMONIZE_DEGREES], with lightness and chroma left alone — so a green contact under a
     * blue wallpaper is a cooler green, not a blue, and the initial keeps its contrast because tone is
     * exactly what did not move. Applied in Oklch rather than Material's HCT: same rule, but Oklab has a
     * closed-form inverse, so twelve tints re-derive at theme time with no solver. A grey accent — a
     * monochrome wallpaper theme — has no hue to steer by and leaves the tint unchanged.
     */
    fun harmonizedToward(accent: Color): AvatarTint =
        AvatarTint(container = harmonize(container, accent), onContainer = harmonize(onContainer, accent))
}

/** The most a harmonized hue moves, in degrees: Material's own cap. */
internal const val MAX_HARMONIZE_DEGREES = 15.0

/** Below this Oklch chroma a colour is a grey, and its hue is numerically meaningless. */
private const val NEUTRAL_CHROMA = 0.01

internal fun harmonize(
    color: Color,
    accent: Color,
): Color {
    val from = Oklch.of(color)
    val to = Oklch.of(accent)
    if (from.chroma < NEUTRAL_CHROMA || to.chroma < NEUTRAL_CHROMA) return color
    val difference = signedDegrees(to.hue - from.hue)
    val rotation = sign(difference) * min(abs(difference) * 0.5, MAX_HARMONIZE_DEGREES)
    return from.copy(hue = from.hue + rotation).toColor()
}

/** [degrees] folded into (-180, 180], so its sign is the shorter way round the wheel. */
@Suppress("MagicNumber") // a full turn and a half turn
private fun signedDegrees(degrees: Double): Double {
    val d = ((degrees % 360.0) + 360.0) % 360.0
    return if (d > 180.0) d - 360.0 else d
}

/**
 * A colour in Oklch — Oklab's lightness, chroma and hue (degrees). Björn Ottosson's 2020 matrices, kept
 * in `Double` so a round trip through [of] and [toColor] lands within 1/255 per channel.
 */
@Suppress("MagicNumber") // the published Oklab matrices and the sRGB transfer-function breakpoints
internal data class Oklch(
    val lightness: Double,
    val chroma: Double,
    val hue: Double,
) {
    /**
     * The nearest sRGB colour: this one if it is in gamut, otherwise the same lightness and hue at the
     * most chroma sRGB can show — the way HCT gamut-maps, and the property the avatar palette needs,
     * because lightness is what carries the initial's contrast. A turned hue can leave the gamut only by
     * a hair (a light saturated yellow turned toward orange), but clamping channels instead would darken
     * it; a binary search on chroma converges to well under a step in [GAMUT_FIT_STEPS] halvings.
     */
    fun toColor(): Color {
        var fit = linearRgb(chroma)
        if (!fit.inGamut()) {
            var low = 0.0
            var high = chroma
            repeat(GAMUT_FIT_STEPS) {
                val mid = (low + high) / 2.0
                if (linearRgb(mid).inGamut()) low = mid else high = mid
            }
            fit = linearRgb(low)
        }
        return Color(red = encode(fit[0]), green = encode(fit[1]), blue = encode(fit[2]))
    }

    /** Linear sRGB channels for this lightness and hue at [chroma], unclamped. */
    private fun linearRgb(chroma: Double): DoubleArray {
        val radians = Math.toRadians(hue)
        val a = chroma * cos(radians)
        val b = chroma * sin(radians)
        val l = (lightness + 0.3963377774 * a + 0.2158037573 * b).pow(3)
        val m = (lightness - 0.1055613458 * a - 0.0638541728 * b).pow(3)
        val s = (lightness - 0.0894841775 * a - 1.2914855480 * b).pow(3)
        return doubleArrayOf(
            4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
            -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
            -0.0041960863 * l - 0.7034186147 * m + 1.7076147010 * s,
        )
    }

    private fun DoubleArray.inGamut(): Boolean = all { it >= -GAMUT_SLACK && it <= 1.0 + GAMUT_SLACK }

    companion object {
        /** Halvings of the chroma range when fitting; 12 puts the answer within 1/4096 of the true edge. */
        private const val GAMUT_FIT_STEPS = 12

        /** Overshoot a channel may have and still count as in gamut: under half an 8-bit step, absorbed by rounding. */
        private const val GAMUT_SLACK = 0.0015

        fun of(color: Color): Oklch {
            val r = linear(color.red)
            val g = linear(color.green)
            val b = linear(color.blue)
            val l = cbrt(0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b)
            val m = cbrt(0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b)
            val s = cbrt(0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b)
            val lightness = 0.2104542553 * l + 0.7936177850 * m - 0.0040720468 * s
            val a = 1.9779984951 * l - 2.4285922050 * m + 0.4505937099 * s
            val bb = 0.0259040371 * l + 0.7827717662 * m - 0.8086757660 * s
            return Oklch(
                lightness = lightness,
                chroma = hypot(a, bb),
                hue = ((Math.toDegrees(atan2(bb, a)) % 360.0) + 360.0) % 360.0,
            )
        }

        /** sRGB transfer function, encoded -> linear. */
        private fun linear(channel: Float): Double {
            val c = channel.toDouble()
            return if (c <= 0.04045) c / 12.92 else ((c + 0.055) / 1.055).pow(2.4)
        }

        /** sRGB transfer function, linear -> encoded; the clamp only absorbs [GAMUT_SLACK]. */
        private fun encode(linear: Double): Float {
            val c = linear.coerceIn(0.0, 1.0)
            return (if (c <= 0.0031308) 12.92 * c else 1.055 * c.pow(1.0 / 2.4) - 0.055).toFloat()
        }
    }
}

/**
 * The tint slot an identity [key] wears — a node id, or the display name for the one case that has no
 * identity (a heard radio author is keyed on its `!hex` label). Deterministic across phones and app
 * versions: `String.hashCode()` is fixed by the Java spec (`s[0]*31^(n-1) + … + s[n-1]`), and a node id
 * is base32 of a SHA-256, so the low bits spread evenly over [count] slots. `floorMod`, because the hash
 * is signed.
 */
fun avatarTintIndex(
    key: String,
    count: Int = AvatarTintsLight.size,
): Int = Math.floorMod(key.hashCode(), count)

// Generated by scripts/gen-avatar-palette.py -- 12 hues 30 degrees apart in HCT.
// Light: disc tone 85 / chroma 20, initial tone 10. Dark: disc tone 30 / chroma 28, initial tone 90.
internal val AvatarTintsLight =
    listOf(
        AvatarTint(container = Color(0xFFF8C8D5), onContainer = Color(0xFF2E131C)), // hue 0
        AvatarTint(container = Color(0xFFFDC8BD), onContainer = Color(0xFF30130E)), // hue 30
        AvatarTint(container = Color(0xFFF8CCAA), onContainer = Color(0xFF2C1602)), // hue 60
        AvatarTint(container = Color(0xFFE7D2A3), onContainer = Color(0xFF241A00)), // hue 90
        AvatarTint(container = Color(0xFFD2D8AD), onContainer = Color(0xFF191E03)), // hue 120
        AvatarTint(container = Color(0xFFC1DCBE), onContainer = Color(0xFF0A200E)), // hue 150
        AvatarTint(container = Color(0xFFB7DCD1), onContainer = Color(0xFF00211A)), // hue 180
        AvatarTint(container = Color(0xFFB7DBE1), onContainer = Color(0xFF002025)), // hue 210
        AvatarTint(container = Color(0xFFBFD8EC), onContainer = Color(0xFF031E2D)), // hue 240
        AvatarTint(container = Color(0xFFCBD4F2), onContainer = Color(0xFF121B31)), // hue 270
        AvatarTint(container = Color(0xFFDBCFF0), onContainer = Color(0xFF1F1730)), // hue 300
        AvatarTint(container = Color(0xFFEBCBE7), onContainer = Color(0xFF281428)), // hue 330
    )

internal val AvatarTintsDark =
    listOf(
        AvatarTint(container = Color(0xFF683848), onContainer = Color(0xFFFFD9E2)), // hue 0
        AvatarTint(container = Color(0xFF6B392F), onContainer = Color(0xFFFFDAD3)), // hue 30
        AvatarTint(container = Color(0xFF653E18), onContainer = Color(0xFFFFDCC1)), // hue 60
        AvatarTint(container = Color(0xFF57440F), onContainer = Color(0xFFFCE09B)), // hue 90
        AvatarTint(container = Color(0xFF434B1B), onContainer = Color(0xFFDEE8A9)), // hue 120
        AvatarTint(container = Color(0xFF2B4E2F), onContainer = Color(0xFFC4EDC3)), // hue 150
        AvatarTint(container = Color(0xFF135044), onContainer = Color(0xFFB4EEDF)), // hue 180
        AvatarTint(container = Color(0xFF0D4E57), onContainer = Color(0xFFB3ECF6)), // hue 210
        AvatarTint(container = Color(0xFF214B64), onContainer = Color(0xFFC8E6FF)), // hue 240
        AvatarTint(container = Color(0xFF38466B), onContainer = Color(0xFFDAE2FF)), // hue 270
        AvatarTint(container = Color(0xFF4C4069), onContainer = Color(0xFFE9DDFF)), // hue 300
        AvatarTint(container = Color(0xFF5D3B5D), onContainer = Color(0xFFFFD6FB)), // hue 330
    )
